import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header style={{ height: "50px", with: "100%", background: "red"}}></header>
      <body className={inter.className}>{children}</body>
      <footer style={{ height: "50px", with: "100%", background: "blue"}}></footer>

    </html>
  )
}
